# -*- coding: utf-8 -*-
"""Project 6: Student Gradebook App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12HLNBlsdpzSZPnQhDYR1iHgWyaWxuI5u
"""

# **Student Name:** Sidra Umer(1377381)

# ** CSV File Handling and Simple Exception Handling in Jupyter Notebook **

import csv
file_name = "student_grades.csv"

try:
    file = open(file_name, "r")
    file.close()

except FileNotFoundError:
    file = open(file_name, "w", newline="")
    writer = csv.writer(file)

    writer.writerow(["Name", "Subject", "Marks", "Grade"])

    file.close()

    print("Gradebook file created.")

def calculate_grade(marks):

    if marks >= 80:
        return "A"
    elif marks >= 70:
        return "B"
    elif marks >= 60:
        return "C"
    elif marks >= 50:
        return "D"
    else:
        return "F"

def add_student():

    try:
        name = input("Enter student name: ")
        subject = input("Enter subject: ")

        if name == "" or subject == "":
            print("Name and subject cannot be empty.")
            return
        marks = int(input("Enter marks from 0 to 100: "))
        if marks < 0 or marks > 100:
            print("Marks must be between 0 and 100.")
            return
        grade = calculate_grade(marks)

        file = open(file_name, "a", newline="")
        writer = csv.writer(file)

        writer.writerow([name, subject, marks, grade])

        file.close()

        print("Student record saved.")
        print("Grade:", grade)

    except ValueError:
        print("Please enter marks as a number.")

def view_students():

    try:
        file = open(file_name, "r")
        reader = csv.reader(file)
        next(reader)
        print("\n===== ALL STUDENT RECORDS =====")
        for row in reader:

            print("Name:", row[0])
            print("Subject:", row[1])
            print("Marks:", row[2])
            print("Grade:", row[3])
            print("--------------------")
        file.close()

    except FileNotFoundError:
        print("Gradebook file not found.")

while True:

    print("\n===== STUDENT GRADEBOOK =====")
    print("1. Add Student")
    print("2. View Students")
    print("3. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        add_student()

    elif choice == "2":
        view_students()

    elif choice == "3":
        print("Gradebook closed.")
        break

    else:
        print("Invalid choice. Enter 1, 2, or 3.")