# -*- coding: utf-8 -*-
"""Project 7:  Student Management System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KKycYMYM9b4uaL99JalZn0CvCBORHRh_
"""

# **Student Name:** Sidra Umer(1377381)

# ** Using a Class, Object, Constructor, Attributes and Methods **

class StudentManagementSystem:

    def __init__(self):
        self.students = []

    def add(self):
        id = input("Student ID: ")
        name = input("Student Name: ")
        age = input("Student Age: ")
        course = input("Enrolled Course: ")

        self.students.append({
            "id": id,
            "name": name,
            "age": age,
            "course": course
        })

        print("Student Added")

    def update(self):
        id = input("Enter ID: ")

        for s in self.students:
            if s["id"] == id:
                s["name"] = input("New Name: ")
                s["age"] = input("New Age: ")
                s["course"] = input("New Course: ")
                print("Updated")
                return

        print("Student Not Found")

    def view(self):
        for s in self.students:
            print(s)

system = StudentManagementSystem()

while True:

    print("\n1. Add Student information")
    print("2. Update Student Information")
    print("3. View Student Information")
    print("4. Exit")

    choice = input("Choice: ")

    if choice == "1":
        system.add()

    elif choice == "2":
        system.update()

    elif choice == "3":
        system.view()

    elif choice == "4":
        break

    else:
        print("Wrong choice")