# -*- coding: utf-8 -*-
"""Project 6: Student Gradebook App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12HLNBlsdpzSZPnQhDYR1iHgWyaWxuI5u
"""

# **Student Name:** Sidra Umer(1377381)

# ** CSV File Handling and Simple Exception Handling **

# importing csv module to use tools in csv library and create file using these tools
import csv
file='student_records.csv'

# Create a csv file
try:
  check_file=open(file,'r')
  check_file.close()
except FileNotFoundError:
  new_file=open(file,'w',newline="")
  writer=csv.writer(new_file)
  writer.writerow(['Name','Subject','Marks','Grade'])
  new_file.close
  print("your desired file created")

#Function for calculating Student marks
def calculate_grade(marks):
  if marks>=80:
    print('A')
  elif marks>=70:
    print('B')
  elif marks>=60:
    print('C')
  elif marks>=50:
    print('D')
  else:
    return 'F'

# adding student information in created csv file
def add_students():
  try:
    name=input("Enter your name")
    subject=input("Enter your subject")
    marks=int(input("Enter your obtained Marks"))
    if name=='' or subject=='':
      print("Yous missed subject or name to enter")
      return
    if marks <0 or marks >100:
      print("marks must be between 0 and 100")
      return
    grade=calculate_grade(marks)

    #saving record in created csv file
    new_file=open(file,'a',newline='')
    writer=csv.writer(new_file)
    writer.writerow([name,subject,marks,grade])
    new_file.close()
    print("Student record has been saved!")
  except ValueError:
    print("Kindly enter marks as a value error")

# check and view the information of added students
def view_student():
  try:
    new_file=open(file,'r')
    read_file=csv.reader(new_file)
    next(read_file)
    print("\n=======All student records=======")
    for row in read_file:
      print("Name",row[0],'\n',"Subject",row[1],'\n',"Marks",row[2],'\n',"Grade",row[3])
    new_file.close()
  except FileNotFoundError:
    print("File not found")

# asking form user to perform actions
while True:
  print('\n========Student Gradebook======','\n',"1. Add Student",'\n',"2. View Student",'\n',"3. Exit")
  Choice=input("enter your choice")
  if Choice=='1':
    add_students()
  elif Choice=='2':
    view_student()
  elif Choice=='3':
    print("Gradebook closed")
    break
  else:
    print("Invalid Choice: Enter 1,2,or 3")

# download file in computer
from google.colab import files
files.download('student_records.csv')
