# -*- coding: utf-8 -*-
"""Project 1:  Simple Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148yHpotl9TNDeAsqZZzOUwWa8HrHziSL
"""

# **Student Name:** Sidra Umer(1377381)

# ** Using a Class, Object, Constructor, Attributes and Methods **

class Calculator:

    def __init__(self, a, b):
        self.a = a
        self.b = b

    def calculate(self):
        self.add = self.a + self.b
        self.sub = self.a - self.b
        self.mul = self.a * self.b
        self.div = self.a / self.b

    def display(self):
        print("Addition:", self.add)
        print("Subtraction:", self.sub)
        print("Multiplication:", self.mul)
        print("Division:", self.div)


a = float(input("First number: "))
b = float(input("Second number: "))

calc = Calculator(a, b)
calc.calculate()
calc.display()