# -*- coding: utf-8 -*-
"""Project 3: Menu Driven Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148yHpotl9TNDeAsqZZzOUwWa8HrHziSL
"""

# **Student Name:** Sidra Umer(1377381)

# ** Using a Class, Object, Constructor, Attributes and Methods **

class Calculator:

    def __init__(self, a, b):
        self.a = a
        self.b = b

    def calculate(self, choice):
        if choice == "+":
            return self.a + self.b
        elif choice == "-":
            return self.a - self.b
        elif choice == "*":
            return self.a * self.b
        elif choice == "/":
            if self.b == 0:
                return "Division by zero is not possible."
            return self.a / self.b


while True:
    print("1: + Addition")
    print("2: - Subtraction")
    print("3: * Multiplication")
    print("4: / Division")
    print("5: 0 Exit")

    choice = input("What operation you want to Perform? Enter the Symbol of Operation(+-*/): ")

    if choice == "0":
        print("Calculator closed.")
        break

    if choice not in "+-*/":
        print("Invalid choice.")
        continue

    a = float(input("First number: "))
    b = float(input("Second number: "))

    calc = Calculator(a, b)
    print("Answer:", calc.calculate(choice))