# -*- coding: utf-8 -*-
"""Project 2:  Temperature Converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148yHpotl9TNDeAsqZZzOUwWa8HrHziSL
"""

# **Student Name:** Sidra Umer(1377381)

# ** Using a Class, Object, Constructor, Attributes and Methods **

class Temperature:

    def __init__(self, value):
        self.value = value

    def c_to_f(self):
        return (self.value * 9 / 5) + 32

    def f_to_c(self):
        return (self.value - 32) * 5 / 9


c = float(input("Enter Celsius value to convert in Farehnheit: "))
obj = Temperature(c)
print("Celsius to Fahrenheit is:", obj.c_to_f())

f = float(input("Enter Fahrenheit value to convert in Celsius: "))
obj = Temperature(f)
print("Farehnheit to Celsius is:", obj.f_to_c())