# -*- coding: utf-8 -*-
"""Project 5: Contact Book Using a Dictionary..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x88pzwCWRVW9Qch3PbQz4rCQc0bWxmFp
"""

# **Student Name:** Sidra Umer(1377381)

# This project adds and searches contacts using a dictionary.

contacts = {}
print("Contact dictionary is ready.")

print("===== CONTACT BOOK =====")
while True:
    print("\n1. Add Contact",'\n',"2. Search Contact",'\n',"3. Exit")

    choice = input("Enter your choice: ")
    if choice == "1":
        name = input("Enter contact name: ")
        phone = input("Enter phone number: ")
        email = input("Enter email address: ")
        if name == "" or phone == "" or email == "":
            print("All information is required.")
        else:
            contacts[name] = {
                "phone": phone,
                "email": email
            }
            print("Contact added successfully.")
    elif choice == "2":
        name = input("Enter contact name to search: ")
        if name in contacts:
            print("Contact found!")
            print("Name:", name)
            print("Phone:", contacts[name]["phone"])
            print("Email:", contacts[name]["email"])

        else:
            print("Contact not found.")
    elif choice == "3":

        print("Contact Book closed.")
        break
    else:
        print("Invalid choice. Enter 1, 2, or 3.")
