# -*- coding: utf-8 -*-
"""project 4: Utility Module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JiWMU9ZWhzXkDXYv3JD2apYAxSrxIiMr
"""

# **Student Name:** Sidra Umer(1377381)

# **Functions:** Factorial, Prime Check, Square Root

# Commented out IPython magic to ensure Python compatibility.
# %%writefile utility.py
# import math
# def factorial(n):
#     ans = 1
#     for i in range(1, n + 1):
#         ans = ans * i
#     return ans
# def prime_check(n):
#     if n < 2:
#         return False
#     for i in range(2, n):
#         if n % i == 0:
#             return False
#     return True
# def square_root(n):
#     return math.sqrt(n)
#

import utility

print(utility.factorial(5))
print(utility.prime_check(7))
print(utility.square_root(25))

print("===== UTILITY PROGRAM =====")

# Factorial
n = int(input("Enter number for factorial: "))

if n < 0:
    print("Negative number not allowed")
else:
    print("Factorial:", utility.factorial(n))

# Prime Check
n = int(input("Enter number to check prime: "))

if utility.prime_check(n):
    print(n, "is prime")
else:
    print(n, "is not prime")

# Square Root
n = float(input("Enter number for square root: "))

if n < 0:
    print("Negative number not allowed")
else:
    print("Square root:", utility.square_root(n))